### ISSUE TITLE
Requirement Conflict 2.1.5 กับ 2.1.16

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#10]
2.1.5 เมื่อผู้ใช้บริการทำการเรียก Taxi สามารถทำการยกเลิกได้  กับ 
2.1.16 เมื่อผู้ใช้บริการทำการจอง Taxi สามารถทำการยกเลิกได้

ตอนรีวิว เพื่อนไม่เข้าใจว่ามันต่างกันยังไง

**Comment by 5731100221-WJ** [comment]
เรียกคือ ไม่ได้จองระบุบว่าคันไหนต้องมารับ แค่เค้ารู้ว่าเราอยุ่ตรงนี้
จองคือ การmatching รถว่ารถคันนี้ต้องมารับเท่านั้น
