### ISSUE TITLE
ข้อ 2.1.8 ผู้ใช้สามารถปรับเปลี่ยนข้อมูล profile ตัวเองได้ 

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#11]
Review
Requirement ข้อนี้ไม่ atomic สามารถแบ่งการเปลี่ยนชื่อ บัตรเครดิต รหัสผ่าน เบอร์โทรศัพท์ และอีเมล แยกเป็นคนละข้อกันได้ เพราะการเปลี่ยนสิ่งใดสิ่งหนึ่งในนี้ไม่เกี่ยวข้องกับการเปลี่ยนของสิ่งอื่น

อยากให้ปุยหาข้อมูลว่า แถมแบบที่ทำตอนแรก กับ ที่เพื่อนรีวิว แล้วก็ตัดสินใจเลย ว่าจะใช้แบบไหน เย้

**Comment by 5731054021-TT** [comment]
ยังคงใช่แบบเดิม ข้อมูลบางอย่างเช่น บัตรเครดิต เกี่ยวข้องกับระบบอื่น ถึงบางข้อมูลไม่เกี่ยวข้องกับการเปลี่ยนแปลงระบบอื่น แต่เราสามารถใช้ประโยชน์ ของ requirement ข้อนี้ได้ 

ps. ถ้ามีอะไรดีกว่า เปลี่ยนเลยได้

**Comment by 5730679121-AP** [comment]
โอเชๆๆๆ  close จ้าาา
