### ISSUE TITLE
แก้ intro 

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#14]
Review
บทนำ กล่าวไม่ชัดเจนควรบอกว่า ระบบใหม่มีกระบวนการอย่างไรในการแก้ปัญหา

**Comment by 5731100221-WJ** [comment]
[Requirements Specification Document.docx](https://github.com/we-inc/mms-road-to-gg-3/files/1404975/Requirements.Specification.Document.docx)
