### ISSUE TITLE
แก้ Class Input ของ Use case "booking car"

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#2]
- เวลาจองรถ สามารถเก็บตำแหน่งเป็น position ร่วมกับ string ด้วยได้หรือไม่ เพราะ string มีความกำกวม และ search ยาก หากทำเป็น position ใน google map แล้วบันทึกไว้ ผู้ให้บริการจะสามารถเข้าใจได้ทันทีว่าไปที่ไหน และทั้งผู้ใช้บริการและผู้ให้บริการยังเข้าใจสถานที่ตรงกันอีกด้วย รวมถึงสามารถ search ได้ง่ายขึ้นด้วย

**Comment by 5731054021-TT** [comment]
ในส่วนนี้เราจะเก็บในรูปแบบ lat long เพื่อเก็บตำแหน่งของบนแผนที่ลงใน Data Base โดยรูปแบบ Decimal(9,6)

**Comment by 5731054021-TT** [comment]
https://docs.google.com/document/d/1bY0eqU52yyfdRLXxr4xYL_N9wb0ovvHkcS0wx5GEGWo/edit
