### ISSUE TITLE
แก้ ER Diagram 

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#21]
Review
	* เนื่องจากใน Class Diagram ไม่มีการระบุตัวแปรอะไรไว้เลย การ review ต่อจากนี้ จะเป็นการสรุปมาจากในส่วนของ Functional Requirement อื่นๆ (ซึ่งแน่นอนว่า ไม่มีตัวแปรใน Class Diagram ทำให้ ER Diagram ไม่มี consistency)
	- ISA ควรจะมาจาก1 แล้วแยกออกเป็น2 ไม่ใช่แยกเป็น ISA 2 อัน
        - ER Diagram ไม่มีการเก็บข้อมูลของ username ไว้ (ตอน login จำเป็นต้องใช้ username กับ password)
	- ในส่วนของ Entity Reservation ไม่ได้มีการเก็บข้อมูล Date กับ Time ที่ต้องการจองไว้ (อาจจะหมายถึง attribute Duration ซึ่งสื่อความหมายได้ไม่ชัดเจน)
	- ในส่วนของ Entity Conversation คือส่วนที่เป็นการเก็บข้อมูลการสนทนา แต่ไม่แน่ใจว่าในระบบมีหรือไม่ เพราะว่าในส่วนการสนทนานี้ไม่ได้มีการบอกถึงในระบบเลย จนกระทั่งมาบอกใน Use Case Description (ใน Use Case Diagram ไม่มี) จึงคิดว่าถ้าเกิดไม่มีส่วนนี้ในระบบ จะเป็นการเก็บข้อมูลที่ไม่มีอยู่จริง/เกินความจำเป็น

**Comment by MikeThuchchai** [comment]
@5730677921-OP Done Naja
