### ISSUE TITLE
แก้ Class Input อีกนิดหน่อย

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#23]
เกี่ยวกับ Class Input
- Input เป็นหลายภาษา แต่ความหมายเดิม (Position กับ ที่หมาย)
- Date สามารถเก็บเป็น Date ได้
- Time  สามารถเก็บเป็น Time ได้
- Date, Time ควรมีการยืนยันว่าสามารถจองได้หรือไม่
- ไม่มี use case ของการ search
- ชื่อไม่ชัดเจนเช่น report ไม่บอกว่าอะไร
- User Logout ไม่ได้???????????

**Comment by 5730679121-AP** [comment]
[summary-SRS-our-group.docx](https://github.com/we-inc/mms-road-to-gg-3/files/1404278/summary-SRS-our-group.docx)

**Comment by 5731100221-WJ** [comment]
https://docs.google.com/document/d/1_14Xbsbwn_22xlH7r4A-DiJ4GJrdh3CvZHhvIrjD05o/edit?usp=sharing
นี่ไม่ใช้อ้อ logout
