### ISSUE TITLE
ทำ Access Control Table 

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#28]
เดี๋ยวทำแบบตารางให้

**Comment by 5731054021-TT** [comment]
https://docs.google.com/document/d/1RsnLmKwvDd-4XxwLqniR_odQN5H5g72e-kPF3Vhg1kg/edit

**Comment by Thanakit-G** [comment]
เสร็จแล้วจ้า เช็คหน่อยนะ
