### ISSUE TITLE
ปรับปรุง Use Case #10 View list all users

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#3]
Use case#10 (ในเอกสารพิมพ์ผิดเป็น #8) “View list all users” คนขับ (ในเอกสารใช้คำนี้) จะดูชื่อคนรอ (ในเอกสารใช้คำนี้) อย่างเดียวไปทำไม คนขับน่าจะอยากรู้ว่าคนรอมี status อย่างไรบ้างด้วย เช่น อยู่ที่ไหน, ใครมาก่อน, รอมานานแค่ไหนแล้ว, จะไปไหน เป็นต้น และน่าจะมีการ sort รายชื่อตามคิวการเรียกหรือตามความใกล้เพื่อให้คนขับสามารถ accept ได้ง่ายๆ ไม่ต้องกดหลายที และเสริมจากข้อที่แล้ว หากเก็บสถานที่เป็น string แล้ว search เป็น string อาจจะลำบาก เนื่องจาก ต่างคนต่างเรียกสถานที่คนละชื่อ และรายละเอียดของสถานที่ก็ต่างกัน

**Comment by Thanakit-G** [comment]
ปรับแก้เลข และเพิ่ม status ให้คนขับดูแล้วจ้า
เรื่อง string อันนี้แก้ไม่ตก ใช้เหมือนเก่าไปก่อนนะ

**Comment by 5730679121-AP** [comment]
แบบว่าเก็บเป็น latitude longtitude อ่ะ
