### ISSUE TITLE
Fucntional Requirement 2.1.8  - แก้

### ISSUE THREAD

**Issue by 5730679121-AP** [we-inc/mms-road-to-gg-3#8]
- re-password invalidity  “ต้องเหมือนทุกตัวใน password” หมายถึงอย่างไร ควรอธิบายให้ละเอียดกว่านี้ 
- เบอร์โทรศัทพ์ invalidity  “มีตัวอักษร” อย่างเดียว ต้องมีการตรวจสอบความยาวของตัวเลขหรือไม่

**Comment by 5731054021-TT** [comment]
1. re-password invalidity ต้องเหมือนทุกตัวใน password กล่าวคือ re-password invalidity ทุกตัวอักษร อักขระ หรือ ตัวเลข จำเป็นจะต้องเหมือน password ทุกตัวที่กรอกข้างต้นก่อนหน้า re-password 
2.  ใน กรณี เบอร์โทรศัทพ์ invalidity การตรวจสอบความยาวหมายเลขทำได้ แต่ จะมีกรณีที่หมายเลขมาจากที่อื่น (เช่น ประเทศอื่น ) การใช้ 080xxxxxxx หรือ +6680xxxxxxx ซึ่งเป็นเบอร์โทรเดียวกัน การตรวจสอบเฉพาะตัวอักษร จะเปิดกว้างมากกกว่า

**Comment by 5731054021-TT** [comment]
https://docs.google.com/document/d/1-MSvFoISzw2OTWAjgfr92yxRv1Jx2_nIEA5XeMGYkeI/edit
